services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  landing:
    image: landing-cci:latest
    container_name: landing-cci

  backend:
    image: backend-cci:latest
    container_name: backend-cci
    secrets:
      - backend-env
    environment:
      - OPENAI_API_KEY=/run/secrets/backend-env
      - DATABASE_URL=/run/secrets/backend-env
      - SUPABASE_DB_PASSWORD=/run/secrets/backend-env
      - SUPABASE_API_KEY=/run/secrets/backend-env
      - SUPABASE_URL=/run/secrets/backend-env
      - RESEND_API_KEY=/run/secrets/backend-env

secrets:
  backend-env:
    file: /home/lralda/secrets/backend.env
